{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "elliptic.name" . }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts: [{{ .Values.ingress.host | quote }}]
      secretName: {{ include "elliptic.name" . }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "elliptic.name" . }}-api
                port: { number: {{ .Values.api.port }} }
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "elliptic.name" . }}-web
                port: { number: {{ .Values.web.port }} }
{{- end }}
