"""Printable HTML export of a dashboard for PDF (COS-139).

Returns a self-contained HTML document (inline styles + bar charts) that
auto-opens the browser print dialog, so a user gets a real PDF via "Save as
PDF" without any server-side PDF dependency — the same approach as notes export.
"""

import html
import uuid

from sqlalchemy.ext.asyncio import AsyncSession

from elliptic.core.deps import OrgContext
from elliptic.modules.dashboards import service

_PALETTE = ["#6366f1", "#0891b2", "#15803d", "#d97706", "#db2777", "#7c3aed", "#dc2626"]


def _as_int(value: object) -> int:
    return value if isinstance(value, int) else 0


def _bars(points: list[dict[str, object]]) -> str:
    values = [_as_int(p.get("value")) for p in points]
    top = max(values) if values else 1
    top = top or 1
    rows = []
    for i, point in enumerate(points):
        key = html.escape(str(point.get("key", "")).replace("_", " "))
        value = _as_int(point.get("value"))
        pct = round(100 * value / top, 1)
        color = _PALETTE[i % len(_PALETTE)]
        rows.append(
            f'<div class="row"><span class="lbl">{key}</span>'
            f'<span class="track"><span class="fill" '
            f'style="width:{pct}%;background:{color}"></span></span>'
            f'<span class="val">{value}</span></div>'
        )
    return "".join(rows) or '<p class="empty">No data.</p>'


async def render_dashboard_html(
    session: AsyncSession, ctx: OrgContext, dashboard_id: uuid.UUID
) -> str:
    dashboard = await service.get_dashboard(session, ctx, dashboard_id)
    widgets = await service.list_widgets(session, ctx, dashboard_id)
    data = {row["widget_id"]: row for row in await service.compute_data(session, ctx, dashboard_id)}

    sections = []
    for widget in widgets:
        widget_data = data.get(widget.id, {})
        raw_points = widget_data.get("points", []) if isinstance(widget_data, dict) else []
        points: list[dict[str, object]] = raw_points if isinstance(raw_points, list) else []
        config = widget.config or {}
        subtitle = html.escape(
            f"{config.get('metric', 'count')} by {config.get('dimension', 'status')}"
        )
        sections.append(
            f'<section class="widget"><h2>{html.escape(widget.title)}</h2>'
            f'<p class="sub">{subtitle}</p>{_bars(points)}</section>'
        )

    body = "".join(sections) or '<p class="empty">This dashboard has no widgets.</p>'
    title = html.escape(dashboard.name)
    org_name = html.escape(ctx.org.name)
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>{title}</title>
<style>
  * {{ box-sizing: border-box; }}
  body {{ font-family: -apple-system, system-ui, sans-serif; color: #18181b; margin: 32px; }}
  header {{ border-bottom: 2px solid #e4e4e7; padding-bottom: 12px; margin-bottom: 24px; }}
  h1 {{ font-size: 22px; margin: 0; }}
  .org {{ color: #71717a; font-size: 13px; }}
  .widget {{ break-inside: avoid; margin-bottom: 28px; }}
  .widget h2 {{ font-size: 15px; margin: 0 0 2px; }}
  .sub {{ color: #71717a; font-size: 12px; margin: 0 0 10px; text-transform: capitalize; }}
  .row {{ display: flex; align-items: center; gap: 10px; margin-bottom: 6px; font-size: 13px; }}
  .lbl {{ width: 140px; text-transform: capitalize; color: #52525b; }}
  .track {{ flex: 1; height: 16px; background: #f4f4f5; border-radius: 4px; overflow: hidden; }}
  .fill {{ display: block; height: 100%; border-radius: 4px; }}
  .val {{ width: 40px; text-align: right; font-variant-numeric: tabular-nums; }}
  .empty {{ color: #a1a1aa; font-size: 13px; }}
  footer {{ margin-top: 32px; color: #a1a1aa; font-size: 11px; }}
  @media print {{ body {{ margin: 0; }} }}
</style></head>
<body onload="window.print()">
  <header><h1>{title}</h1><div class="org">{org_name}</div></header>
  {body}
  <footer>Generated by Elliptic</footer>
</body></html>"""
